CREATE TABLE role (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(15) NOT NULL UNIQUE
);

CREATE TABLE user (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(20) NOT NULL UNIQUE,
	password VARCHAR(60) NOT NULL,
	role_id BIGINT REFERENCES role(id),
	enabled BOOLEAN NOT NULL
);